blogapp/urls.py
from django.urls import path
from .views import *

app_name = "blogapp"

urlpatterns = [

    path('', HomeView.as_view(), name='home'),
    path('about/', AboutView.as_view(), name='about'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('nepal/', NepalView.as_view(), name='nepal'),
    path('blog/list/', BlogListView.as_view(), name='bloglist'),
    path('blog/event/', EventListView.as_view(), name='eventlist'),
    path('news/list/', NewsListView.as_view(), name='newslist'),
    path('blog/create/', BlogCreateView.as_view(), name='blogcreate'),
    path('blog/detail/', BlogDetailView.as_view(), name='blogdetail'),
    path('blog/<int:pk>/update/', BlogUpdateView.as_view(), name='updateblog'),
    path('blog/<int:pk>/delete/', BlogDeleteView.as_view(), name='deleteblog'),
    path('news/create', NewsCreateView.as_view(), name='newscreate'),
    path('news/<int:pk>/update/', NewsUpdateView.as_view(), name='updatenews'),
    path('news/<int:pk>/delete/', NewsDeleteView.as_view(), name='deletenews'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('blog/<int:pk>/comment', BlogCommentCreateView.as_view(),
         name='blogcommentcreate'),
    path('search/', SearchView.as_view(), name='search'),






]

blogproject/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogapp.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogapp/models.py
from django.db import models


class Blog(models.Model):
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to='blogs')
    contents = models.TextField()
    author = models.CharField(max_length=200)
    date = models.DateTimeField(auto_now_add=True)
    viewcount = models.PositiveIntegerField(default=0)

    def __str__(self):

        # to return the title of blog page(for return date,do,self.date)
        return self.title + "(" + self.author + ")" + str(self.date) + str(self.id)


class Event(models.Model):
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to='events')
    contents = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class Catagory(models.Model):
    title = models.CharField(max_length=50)
    image = models.ImageField(upload_to='catagory')

    def __str__(self):
        return self.title


class News(models.Model):
    title = models.CharField(max_length=200)
    # catagory = models.ForeignKey(Catagory,on_delete=models.CASCADE)  #Catagory helps to create a relations with the above Catagory class(for many to one)
    # Catagory helps to create a relations with the above Catagory class(for many to many relatiosn)
    catagory = models.ManyToManyField(Catagory)
    image = models.ImageField(upload_to='news')
    detail = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    author = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return self.title


class Message(models.Model):
    name = models.CharField(max_length=200)
    phone = models.CharField(max_length=20)
    # null and blank are succesively
    email = models.EmailField(max_length=50, null=True, blank=True)
    subject = models.CharField(max_length=50)
    message = models.CharField(max_length=200)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Comment(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    commenter = models.CharField(max_length=50)
    email = models.EmailField()
    comment = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.commenter

templates/about.html
{% extends 'base.html' %}
{% load static%}

{% block content%}

<h3>Hello, This is About Page !!!</h3>

{% endblock%}

templates/base.html
{%  load static %}
<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
	<title>Base</title>
</head>
<body class="container">
	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="nav-link" style='color: white'href="#">MY BLOG</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link " href="/contact/">Contact Page</a>
      </li>
     
      <li class="nav-item active">
        <a class="nav-link " href='/about/' tabindex="-1" aria-disabled="true">About Page</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/blog/list">Blog List <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/blog/event">Event List <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/blog/create/">Blog Create <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/news/list/">Blog News<span class="sr-only">(current)</span></a>
      </li>
    </ul>




   <!--  search button form -->
    <form class="form-inline" action='/search/' method="GET">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search"   name="search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
   </form>

   
  
  </div>
</nav>




	<p class="text-info">
		{% if request.user.is_authenticated %}

		{{ request.user}}
    <a href="/logout">Logout</a>
		{% else %}
		<a href="/login/">Login</a>
		{% endif %}
 

	<!-- <a href="/">Home</a> -->
	<!-- <a href="< /contact --><!-- ">Contact Page</a> --> 
	<!-- <a href="/about"> About Page</a>
	<a href="/nepal">Nepal Page</a>
	<a href="/blog/list">Blog List</a>
	<a href="/blog/event/">Event List</a>
	<a href="/blog/create/">Blog Create</a>
	<a href="/news/list/">Blog News</a> -->

	</p>



	{% block content %}


	{% endblock %}
		

</body>
</html>

templates/blogcreate.html
{%  extends 'base.html' %}
{% load static %}

{% block content %}
<div class="row">
	<div class='col-md-6'>
		<h1>Add new blog</h1>   
		 	<form method='POST' enctype="multipart/form-data">
		 
		    {% csrf_token %} 	

		    {{ form.as_p}}	
		    <button>submit</button>
		</form>  
	</div>
	<div class='col-md-6'>
		<h1> blogs</h1>   
		{% for blog in blogs|slice:'3' %}
		<div class="row">
			<div class=col-md-6>
				<img src="{{blog.image.url}}" class="img-fluid">
				
			</div>

			<div class="col-md-6">
				
			
				<li>{{blog.title}}</li>
			</div>

		</div>
		{% endfor %}
	</div>
</div>




{% endblock %}
 <!-- by default get method enctype for  media files(image,pdf,audio) -->

templates/blogdelete.html
{%  extends 'base.html' %}
{% load static %}

{% block content %} 
<form method='POST' action='/blog/{{object.id}}/delete/'>
{% csrf_token %}
<h4>Do you want to delete ??? {{object.title}}</h4>
<button>Delete</button> 
<a href="/blog/list">Cancel</a>
</form> 






{% endblock %}

templates/blogdetail.html
	{% extends 'base.html' %}
	{%  load static %}



	{% block content %}

	{{blog.title}}(viewed {{blog.view_count}} times	)



	<h3>{{blogdetail.title}}</h3>

	<h3><img src="{{blogdetail.image.url}}">image</h3>

	<h3>{{blogdetail.content}}</h3>

	<a href="/blog/{{blogdetail.pk}}/update">Update</a>
	<a href="/blog/{{blogdetail.pk}}/delete">delete</a>


	<h1>All comments</h1>


	{% for comment in blogdetail.comment_set.all %}
	<li>{{comment.user}}</li>
	<li>{{comment.message}}</li>
	{% endfor %}
	<form method="post" action="{% url 'blogapp:comment' blogdetail.id %}">
		{% csrf_token %}
		{{commentform.as_p}}
		<button>submit</button>
		

	</form>



	{% endblock %}

templates/commentcreate.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<form method='POST'>
	
	{% csrf token %}
	{{ commentform.as_p}}

	<button>Post Comment</button>




</form>














{% end block %}

templates/contact.html
{% extends 'base.html' %}
{% load static%}

{% block content%}

<h3>Hello, This is Content Page !!!</h3>
<form method="POST">
	{% csrf_token %}
	
	{{form.as_p}}
	<button>SUbmit data</button>



</form>


{% endblock%}

templates/eventlist.html
{% extends 'base.html' %}

{% load static%}

{% block content %}
<h1>List of Events</h1>
{% for event in allevent%}

<h1>{{ event.title}}</h1>

<p>{{ event.contents}}</p>

<img src="{{event.image.url}}" width='200'>
<br>
<br>


{% endfor %}

{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% load static%}

{% block content%}

<h3>Hello, This is Homepage !!!</h3>
<br>
<h1>Name of the Blog</h1>
{% for blog in blogs %}
<li>{{blog.title}}</li>

{% endfor %}

<h1>Name of the Event</h1>


{% for event in events %}
<li>{{event.title}}</li>

{% endfor %}


{% endblock%}

templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h4>Login Form</h4>

{% if error %}
<li class='text-danger'>{{ error}}</li>
{% endif %}



<form  method='POST' >
	
{% csrf_token%}
<label>Username</label>
{{form.username}}
<br>
<label>Password</label>
{{form.password}}
<br>
<button>Login</button>


</form>







{% endblock %}

templates/nepal.html
{% extends 'base.html' %}
{% load static%}

{% block content%}

<h3>Hello, This is about Nepal Page !!!</h3>

{% endblock%}

templates/newscreate.html
{%  extends 'base.html' %}
{% load static %}

{% block content %}

<h1>Add new News</h1>   
 <form method='POST' enctype="multipart/form-data">
 
 {% csrf_token %} 	

 {{ form.as_p}}	
<button>submit</button>
</form>  



{% endblock %}
 <!-- by default get method enctype for  media files(image,pdf,audio) -->

templates/newsdelete.html
{%  extends 'base.html' %}
{% load static %}

{% block content %} 
<form method='POST' action='/news/{{object.id}}/delete/'>
{% csrf_token %}
<h4>Do you want to delete ??? {{object.title}}</h4>
<button>Delete</button> 
<a href="/news/list">Cancel</a>
</form> 






{% endblock %}

templates/newslist.html
{% extends 'base.html'%}
{% load static%}

{% block content %}


<h1>List of news</h1>

{% for news in allnews %} <!-- for-loop, for viewing content of news-->


<h4>{{ news.title}}</h4> <!-- double curlybraces for variables data -->


<p>{{ news.detail}}</p>

<img src="{{news.image.url}}" width='200'>

<a href="/News/{{news.id}}/update/">Update</a>
<a href="/News/{{news.id}}/delete/">Delete</a>

{% endfor %}

{% endblock %}